project:
  type: website
  preview:
    port: 6492
  resources: 
    - ./assets/*.png
    - ./assets/*.js.map
    - ./assets/*.mp3
    - ./assets/*.wav


website:
  title: "Fifty-Six Lily Pads"
  site-url: "https://dhmmasson.github.io/lilyFrogs/"
  favicon: "assets/frog-pink.png"
  open-graph: 
    locale: "en_US"    
  description: "My Entry for Ludum Dare 56. A game made in 48 hours."
  
  twitter-card: 
    card-style: "summary_large_image"
    creator: "@dhmmasson"
  page-footer: 
    left: 
      - text: "Ludum Dare 56 (2024) - Dimitri Masson - MIT License"
    right:
      - text: "Star the project on GitHub"
      - icon: github
        href: https://github.com/dhmmasson/lilyFrogs

format:
  html:
    theme:
      - sketchy
      - assets/ld56-theme.scss
    css: styles.css
    toc: false
    fontsize: 1.1em
    linestretch: 1.7
    page-layout: full
    email-obfuscation: javascript
    appendix-cite-as: display
    title-block-style: manuscript
    image: "assets/coverArt.png"
    image-width: "640px"
    image-height: "512px"
    license: "MIT"
    include-in-header: 
      text: |
        <meta property="og:url" content="https://dhmmasson.github.io/lilyFrogs/">
        <meta property="og:type" content="website">
        <meta property="og:logo" content="assets/frog-pink.png">

