project:
  type: website
  preview:
    port: 6492
  resources: 
    - ./assets/*.png
    - ./assets/*.js.map
    - ./assets/*.mp3
    - ./assets/*.wav


website:
  title: "LD56"
  site-url: "https://dhmmasson.github.io/LD56"
  sidebar:
    style: docked
    alignment: right
    search: false
    contents:
      - text: "Play"
        href: index.qmd
      - about.qmd
      - text: "@dhmmasson"
        href: "https://dhmmasson.github.io/"
    tools:
      - icon: github
        href: https://github.com/dhmmasson

format:
  html:
    theme:
      - sketchy
      - assets/ld56-theme.scss
    css: styles.css
    toc: false
    fontsize: 1.1em
    linestretch: 1.7
