project:
  type: website

website:
  title: "LD56"
  site-url: "https://dhmmasson.github.io/LD56"
  navbar:
    left:
      - href:  "https://dhmmasson.github.io/"
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/dhmmasson

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



