project:
  type: website

website:
  title: "LD56"
  site-url: "https://dhmmasson.github.io/LD56"
  sidebar:
    style: docked
    alignment: right
    search: false
    contents:
      - text: Home
        href:  "https://dhmmasson.github.io/"
      - about.qmd
    tools: 
      - icon: github
        href: https://github.com/dhmmasson
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



